### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tsyroid** [mrjones2014/op.nvim#10]
Users need some pre-req guidance to keep the install/user-experience positive. I think this could be accomplished by providing some detailed prerequisites (because I'm stupid sometimes, and I'm always forgetting about ASS-U-MEs).

Because I don't have a full handle (yet) on the capabilities of this plugin, rather than do a PR thing, I'll just throw some rough notes into the ring to edge the process forward.

Not at all complete or polished, but should be enough to give you a sense of where I'm coming from

<img width="563" alt="screen1" src="https://user-images.githubusercontent.com/867354/183223101-5e19db71-854b-4eb6-ab95-924d7c8d3340.png">

<img width="563" alt="screen2" src="https://user-images.githubusercontent.com/867354/183223119-4611f8a4-e594-4c95-aae2-7b99d7a9f93e.png">

[op-nvim.md](https://github.com/mrjones2014/op.nvim/files/9273966/op-nvim.md)

Nice start, Matt. This one's already a keeper for me.

**Comment by mrjones2014** [comment]
I think I've got everything in the README.md that you've mentioned now. Let me know otherwise.
